---
title: "ND PIER Data Visualization Workshop"
description: |
  Worked Examples in R and ggplot2.
author:
- name: Kieran Healy
  url: https://kieranhealy.org
  affiliation: Duke University
  affiliation_url: https://sociology.duke.edu
date: "`May 2023`"
output: md_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Supporting files for the workshop

This repository contains the data, code, and slides for the workshop. It's an RStudio project, so to launch it, double-click on `nd-pier.Rproj` and RStudio will open with this project ready to go. 

## What's here

### A `workshop_notes.Rmd` document 

An RMarkdown document to get you started on taking your own notes. 

### The `code/` folder

All of the code snippets from the slides, extracted as R script files.

### The `patchplot/` folder

A more advanced example showing how to compose some relatively complex plots and repeatedly walk them out to files.

### The `pdf_slides/` folder

PDF versions of the slides. 

### The `slides/` folder

RMarkdown files and various supporting files to generate HTML versions of the slides. The HTML versions can be viewed in a web browser. The RMarkdown files require various supporting packages, so do not expect them to work out of the box. But if you install the packages that RStudio asks you to when you load one of the slide files, together with [kjhslides](https://kjhealy.github.io/kjhslides/) and [covdata](https://kjhealy.github.io/covdata/), you should be able to compile the Rmd files and view the results in an external browser. Click the "Show in new Window" icon from the Viewer tab---the one that looks like a tiny browser window with an arrow on top; it's to the right of the tiny broom icon---to launch the slides in your browser. When you first launch, give your browser a minute to organize everything, because it’s going to be a large file, so this will be like waiting for a very big webpage to load. You may see things first appear in Times New Roman and then be replaced by the correct font once the javascript catches up. Press "o" on your keyboard to get an overview of all the slides.




